version: '3.5'

volumes:
  logs:
  iam_mysql_data:
  trust:

services:

  db:
    image: mysql:5.7
    volumes:
     - iam_mysql_data:/var/lib/mysql
    # The setting below enables custom configuration
    # that turns on the MySQL query log
    #   - ./compose/mariadb:/etc/mysql/conf.d
    
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: iam
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: iam

    ports:
      - "3306:3306"

  trust:
    image: indigoiam/trustanchors
    command: /bin/true
    volumes:
      - trust:/etc/grid-security/certificates
    environment:
      FORCE_TRUST_ANCHORS_UPDATE: 1


  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  iam-mail-server:
    image: mailhog/mailhog
    container_name: mailhog-smtp
    ports:
      - "1025:1025"
      - "8025:8025"
  iam-be:
    container_name: iam-be
#    image: indigoiam/iam-login-service
    image: basbs/iam-login-service
#    build:
#      context: .
#      dockerfile: ./iam-login-service/docker/Dockerfile

    environment:
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1044 -Dspring.profiles.active=prod -debug
      IAM_JAR: /code/iam-login-service/target/iam-login-service.war
      IAM_HOST: iam.local.io
      IAM_BASE_URL: https://iam.local.io
      IAM_ISSUER: https://iam.local.io/
      IAM_FORWARD_HEADERS_STRATEGY: native
#      IAM_NOTIFICATION_DISABLE: "true"
      IAM_KEY_STORE_LOCATION: "file:///code/keystore.jwks"
      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd

#      IAM_GOOGLE_CLIENT_ID: ${IAM_GOOGLE_CLIENT_ID}
      IAM_GOOGLE_CLIENT_ID: ${IAM_GOOGLE_CLIENT_ID}
      IAM_GOOGLE_CLIENT_SECRET: ${IAM_GOOGLE_CLIENT_SECRET}

      IAM_IAM_TEST_CLIENT_ID: "Mm5NRf2iLfIcA0-1lzG0sc7QiARSR4j5QqSrHgnT7OVoClrFMz3RyiaHT8f7ga0CVoreZYn8HmNEVM3ormBeZQ"
      IAM_IAM_TEST_CLIENT_SECRET: "426bf95a-d561-41cb-81c9-f21b7ee4dafb"

      IAM_JWT_DEFAULT_PROFILE: wlcg

      ## SMTP mail server settings

      # SMTP server hostname
      IAM_MAIL_HOST: mailhog-smtp

      # SMTP server port 
      IAM_MAIL_PORT: 1025

      # SMTP server username
      IAM_MAIL_USERNAME:

      # SMTP server password
      IAM_MAIL_PASSWORD:

      ## IAM notification settings

      # Should the notification server be disabled?
      # When set to true, notifications are not sent to the mail server (but
      # printed to the logs)
      IAM_NOTIFICATION_DISABLE: "false"

      # The email address used as the sender in IAM email notifications
      IAM_NOTIFICATION_FROM: indigo@localhost

      # The email address used as the recipient in IAM email notifications
      IAM_NOTIFICATION_ADMIN_ADDRESS: indigo-alerts@localhost

      # Notification policy for account requests. The default value is notify-address
      # meaning that notifications just arrive to the email address
      # specified above. Set to notify-admins if you want to notify
      # all IAM admins or to notify-address-and-admins to combine the two behaviors
      IAM_NOTIFICATION_ADMIN_NOTIFICATION_POLICY: notify-address

      # Notification policy for group requests. Default value notifies both
      # admins and group managers. Set to notify-gms if you want to notify only group managers
      IAM_NOTIFICATION_GROUP_MANAGER_NOTIFICATION_POLICY: notify-gms-and-admins

      # Time interval, in milliseconds, between two consecutive runs of IAM notification 
      # dispatch task 
      IAM_NOTIFICATION_TASK_DELAY: 30000

      # Retention of delivered messages, in days
      IAM_NOTIFICATION_CLEANUP_AGE: 30

      # IAM_SAML_IDP_METADATA: file:///code/compose/metadata/test-idp.cloud.cnaf.infn.it.metadata.xml
      # IAM_SAML_ENTITY_ID: urn:iam:iam-devel
      # IAM_SAML_ENTITY_ID: https://iam.local.io
      
      # IAM_RCAUTH_ENABLED: "false"
      # IAM_RCAUTH_CLIENT_ID: ${IAM_RCAUTH_CLIENT_ID}
      # IAM_RCAUTH_CLIENT_SECRET: ${IAM_RCAUTH_CLIENT_SECRET}
      # IAM_RCAUTH_ISSUER: ${IAM_RCAUTH_ISSUER}

    ports:
      - "1044:1044"

    depends_on:
      - db

    volumes:
      - trust:/etc/grid-security/certificates
      - logs:/var/log/iam
      - .:/code:ro
      - /dev/urandom:/dev/random
        # - ./compose/custom-logging/logback-spring.xml:/indigo-iam/logback-spring.xml:ro
        # - ./compose/metadata/iam.local.io.metadata.xml:/indigo-iam/iam.local.io.metadata.xml:ro
        # - ./compose/metadata/spid-idp.example.metadata.xml:/indigo-iam/spid-idp.example.metadata.xml:ro
        # - ./compose/custom-saml/application-saml.yml:/indigo-iam/config/application-saml.yml:ro
        # - ./compose/multiple-oidc-providers/application.yml:/indigo-iam/config/application.yml

  client:
    build:
      context: .
      dockerfile: ./iam-test-client/docker/Dockerfile

    container_name: client

    environment:
      TZ: Europe/Rome
      IAM_CLIENT_PORT: 8080
      IAM_CLIENT_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1045
      IAM_CLIENT_ISSUER: https://iam.local.io/
      IAM_CLIENT_REDIRECT_URIS: https://iam.local.io/iam-test-client/openid_connect_login
      IAM_FORWARD_HEADERS_STRATEGY: native
      IAM_CLIENT_TLS_USE_GRID_TRUST_ANCHORS: "true"
      #IAM_CLIENT_EXT_AUTHN_HINT: saml:exampleIdp
      IAM_CLIENT_JAR: /code/iam-test-client/target/iam-test-client.jar

    ports:
      - "1045:1045"

    volumes:
      - trust:/etc/grid-security/certificates
      - .:/code:ro

  iam:
    build:
      context: ./docker/nginx/

    depends_on:
      - iam-be
      - client

    dns_search: local.io

    container_name: iam

    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam
      NGINX_PORT: 443

    ports:
      - "443:443"

    volumes:
      - /dev/urandom:/dev/random

    networks:
      default:
        aliases:
          - iam.local.io
